// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Btn: typeof import('./src/components/Btn.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CustomCheckbox: typeof import('./src/components/CustomCheckbox.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    ErrorText: typeof import('./src/components/ErrorText.vue')['default']
    Index: typeof import('./src/components/CustomCheckbox/Index.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewTodoForm: typeof import('./src/views/Todo/components/NewTodoForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagSelector: typeof import('./src/components/TagSelector.vue')['default']
    Todolist: typeof import('./src/views/Todo/Todolist.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
